version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: snapurl:latest
    ports:
      - "3333:3333"
    environment:
      DATABASE_URL: "mysql://root:@localhost:3306/test"
      PORT: "3333"
    restart: unless-stopped

    # REQUIRED for Linux hosts
    extra_hosts:
      - "host.docker.internal:host-gateway"
