version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: snapurl:latest
    ports:
      - "3333:3333"
    environment:
      DATABASE_URL: "mysql://snapurl_user:snapurl_password@host.docker.internal:3306/snapurl?charset=utf8mb4&timezone=UTC"
      PORT: "3333"
    restart: unless-stopped

    # REQUIRED for Linux hosts
    extra_hosts:
      - "host.docker.internal:host-gateway"
