version: "3.8"

services:
  app:
    container_name: snapurl_app
    build:
      context: .
      dockerfile: Dockerfile
    image: snapurl:latest
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"
    restart: unless-stopped

    # Required for Linux to access host DB
    extra_hosts:
      - "host.docker.internal:host-gateway"
